### ISSUE TITLE
Error with few reads

### ISSUE THREAD

**Issue by lucacozzuto** [Psy-Fer/deeplexicon#20]
Dear authors,

some of the reads fail giving me this error:

```
info: dRNA_segmenter: no seg found: 00cbd24b-da23-4463-b397-2372caad18be
```

not sure why. Can you help me in understanding? Thanks

Luca

**Comment by Psy-Fer** [comment]
Hello,

So if you take those reads, and look at their signal, chances are they are a little messed up at the start, where the adapter signal lies.

If the segmentation algorithm can't find a suitable segment that should represent the adapter (which is what is modified into a barcode), then it gives this error.

You will see this in every run, as a small % of reads will have messy signal in that region for any number of reasons.

If you are seeing more than 15% of your data being missed though, that would be something to look into, otherwise, it's more an issue with the sequencing/ONT software than deeplexicon. 

I hope that helps.

James

**Comment by lucacozzuto** [comment]
Thanks a lot. I was wondering if they can be added as "FAILED" or something like that in the report. I think this information can be valuable.

**Comment by Psy-Fer** [comment]
The same report as the output, or in a separate report? if they are in the same, they will appear in groups before any of the rest of the data as they are found during segmentation.

**Comment by lucacozzuto** [comment]
I think is fine in the same report, no? So that when you demultiplex they can be separated from the other and analyzed independently

**Comment by enovoa** [comment]
I believe this is now sorted out :) Thanks!
